<div class="post <?= $post->type; ?>" id="<?= $post->id; ?>">
    <div class="post-info">
        <?php if ($post->subject) { ?>
            <span class="subject"><?= $post->subject; ?></span>
        <? } ?>
        <?php if ($post->sage) { ?>
            <span class="sage">Sage</span>
        <? } ?>
        <span class="name"><?= $post->name; ?></span>
        <span class="time"><?= $post->time; ?></span>
        <span class="link"><?= $post->link; ?></span>
    </div>

    <?php if ($post->getFiles()) { ?>
        <div class="post-file left">
        <?php foreach ($post->getFiles() as $file) { ?>
            <a href="<?= $file->getLink('origin'); ?>" data-image-expand="true">
                <img src="<?= $file->getLink('thumb'); ?>" alt="file-<?= $file->type; ?>-<?= $file->id; ?>">
                <span class="file-info">(1230x790) <?= $file->type; ?></span>
            </a>
        <? } ?>
        </div>
    <? } ?>

    <div class="post-text">
       <?= $post->text; ?>
    </div>
</div>
<div class="clear"></div>
