<div class="board-content">

	<div class="thread-box" data-type="thread-<?= $thread->id?>">
		<?php
			$this->partial("common/chan_thread", [ 'thread' => $thread, 'open' => true ]);
			foreach ($thread->getReply() as $post)
				$this->partial("common/chan_post", [ 'post' => $post]);
		?>
	</div>
	<hr>

</div>

<div class="board-nav">
	<span>
		<?= $this->tag->linkTo([
			$this->url->get([ 'for' => 'chan-board-link', 'board' => $thread->board ]),
			'Назад',
			'class' => 'btn'
		]); ?>
		<?= $this->tag->linkTo([
			'#',
			'Вверх',
			'local' => false,
			'data-scroll' => 'up',
			'class' => 'btn'
			]); ?>
		<?= $this->tag->linkTo([
			'#',
			'Обновить',
			'local' => false,
			'data-thread-refresh' => $thread->id,
			'class' => 'btn'
		]); ?>
	</span>
</div>