<div class="board-content">

	<div class="thread-box" data-type="thread-<?= $thread->id?>">
		<?php
			$this->partial("common/chan_thread", [ 'thread' => $thread, 'open' => true ]);
		?>
		<div class="thread-replys">
			<?php
				foreach ($thread->getReply() as $post)
					$this->partial("common/chan_post", [ 'post' => $post]);
			?>
		</div>
	</div>
	<hr>

</div>

<div class="board-nav">
	<span>
		<?= $this->tag->linkTo([
			['for' => 'chan.board', 'board' => $thread->board],
			'Return',
			'class' => 'btn'
		]); ?>
		<?= $this->tag->linkTo([
			'#',
			'Refresh thread',
			'local' => false,
			'data-thread-refresh' => $thread->id,
			'class' => 'btn'
		]); ?>
	</span>
</div>