<?php use Phalcon\Tag as Tag; ?>

<script type="text/javascript">
	var is_thread = <?= (isset($thread_id) && $thread_id != 0) ? 'true' : 'false' ?>;
</script>

<div class="board">
	
	<h2 class="board-name">
		<?= Tag::linkTo([ $this->url->get([ 'for' => 'board-link', 'board' => $board->slug ]), $board->name ]); ?>
		<?php if ($board->description) { ?>
			<span class="board-desc"><?= $board->description; ?></span>
		<? } ?>
	</h2>
	<hr>
	<div class="board-add">
		<?php $this->partial("partial/add", [ 'thread_id' => $thread_id ]); ?>
	</div>
	<hr>
	<div class="board-content">
		<?= $this->getContent(); ?>
	</div>
	
</div>